[build]
  functions = "netlify/functions/"

[functions]
node_bundler = "esbuild"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
	Access-Control-Allow-Headers = "Content-Type"
	Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
	Content-Type = "application/json"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200