[build]
  functions = "netlify/functions/"

# Include all files in all functions
[functions]
  included_files = ["netlify/functions/lib/**"]

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
